/*
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
DO NOT EDIT THIS FILE DO NOT EDIT THIS FILE
*/

package blezerbot;
import battlecode.common.*;

public strictfp class RobotPlayer {
    static RobotController rc;
    static int turnCount;
    public static void run(RobotController rc) throws GameActionException {
        RobotPlayer.rc = rc;
        while (true) {
            turnCount += 1;
            try {
                switch (rc.getType()) { /*{%SWITCH%}*/ }
                Clock.yield();
            } catch (Exception e) {
                System.out.println(rc.getType() + " Exception");
                e.printStackTrace();
            }
        }
    }
    /*{%CODE%}*/
}
